## 1. Tensorflow 基础API

- 基础数据类型
    1. tf.constant
    2. tf.string
    3. tf.ragged.constant, tf.SpareTensor, tf.Variable
- 自定义损失函数
    1. tf.reduce_mean
- 自定义层次
    1. keras.layers.lambda
    2. 继承法
- TF.function
    1. tf.function
    2. tf.autograph.to_code
    3. get_concrete_function
- GraphDef
    1. get_operations
    2. get_operation_by_name
    3. get_tensor_by_name
    4. as_graph_def
- 自动求导
    1. tf.GradientTape
    2. optimzier.apply_gradients

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
% matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.3.0
sys.version_info(major=3, minor=7, micro=11, releaselevel='final', serial=0)
matplotlib 3.4.2
numpy 1.18.5
pandas 1.3.3
sklearn 1.0
tensorflow 2.3.0
tensorflow.keras 2.4.0


### 1. tf.constant

#### 1.1 常量的定义以及索引操作

In [3]:
# 定义常量
t = tf.constant([[1., 2., 3., ], [4., 5., 6.]])

# tensorflow 的索引
print(t)
# 打印 从第二列开始到最后一列的数据
print(t[:, 1:])
# 获取第二列的数据
print(t[..., 1])

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)


#### 1.2  tensorflow 的基本操作

In [4]:
# tensorflow 的基本操作
print(t + 10)  # tensor 中的每个数据都加10
print(tf.square(t))  # 对t中的每个数据求平方
print(t @ tf.transpose(t))  # t 和他的转置相乘 (2,3) * (3,2)

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


#### 1.3 tf和numpy的相互转换

In [7]:
print(t.numpy())
print(tf.square(t))

np_t = np.array([[1., 2., 3.], [4., 5., 6.]])
print(tf.constant(np_t))

[[1. 2. 3.]
 [4. 5. 6.]]
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


#### 1.4 标量

In [11]:
# 定义标量(标量一般是0维的)
t = tf.constant(3.2)
print(t)
print(t.numpy())
print(t.shape)

tf.Tensor(3.2, shape=(), dtype=float32)
3.2
()


### 2. tf.string和ragged_tensor

#### 2.1 string存储

In [15]:
t = tf.constant("hello")
print(t)

# 打印字符的长度, 注意这个长度是
print(tf.strings.length(t))

tf.Tensor(b'hello', shape=(), dtype=string)
tf.Tensor(5, shape=(), dtype=int32)
